const UserTypes = {
    USER_OTP_START: 'USER_OTP_START',
    USER_OTP_SUCCESS: 'USER_OTP_SUCCESS',
    USER_OTP_FAIL: 'USER_OTP_FAIL',


    USER_SIGNUP_START: "USER_SIGNUP_START",
    USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
    USER_SIGNUP_FAIL: "USER_SIGNUP_FAIL"
}

export default UserTypes;